import {
  Patient,
  Appointment,
  ClinicalConsultation,
  MedicalAidClaim,
  SpecialistReferral,
  LocumSlotRequest,
  DoctorCPDCertificate,
  PatientMedicineReminder,
  AuditLog,
  ICD10Code,
  NappiMedication,
  TariffItem,
} from '../types';

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-001',
    fullName: 'Sipho Zulu',
    idNumber: '8503145890082',
    dob: '1985-03-14',
    gender: 'Male',
    phone: '+27 82 555 0192',
    email: 'sipho.zulu@iafrica.com',
    address: '42 Jan Smuts Avenue, Parktown, Johannesburg, 2193',
    medicalAidName: 'Discovery Health',
    medicalAidNumber: '902184729',
    dependantCode: '00',
    planName: 'Classic Comprehensive',
    savingsBalanceZAR: 6850.00,
    chronicAuthorised: true,
    chronicConditions: ['Hypertension', 'Gout'],
    allergies: ['Penicillin', 'Sulphonamides'],
    emergencyContact: {
      name: 'Nandi Zulu',
      relationship: 'Spouse',
      phone: '+27 82 555 0193',
    },
    tags: ['High Risk', 'Chronic PMB', 'Discovery Diamond'],
    registeredDate: '2023-01-15',
  },
  {
    id: 'pat-002',
    fullName: 'Lerato Mokoena',
    idNumber: '9207180124088',
    dob: '1992-07-18',
    gender: 'Female',
    phone: '+27 71 444 8821',
    email: 'lerato.mokoena@gmail.com',
    address: '15 Oxford Road, Rosebank, Johannesburg, 2196',
    medicalAidName: 'GEMS',
    medicalAidNumber: '800319482',
    dependantCode: '00',
    planName: 'Ruby Option',
    savingsBalanceZAR: 4120.00,
    chronicAuthorised: true,
    chronicConditions: ['Bronchial Asthma', 'Atopic Eczema'],
    allergies: ['Aspirin (NSAIDs)'],
    emergencyContact: {
      name: 'Kagiso Mokoena',
      relationship: 'Brother',
      phone: '+27 71 444 8822',
    },
    tags: ['Asthma Action Plan', 'Telehealth Regular'],
    registeredDate: '2023-05-20',
  },
  {
    id: 'pat-003',
    fullName: 'Johan van der Merwe',
    idNumber: '7411055018084',
    dob: '1974-11-05',
    gender: 'Male',
    phone: '+27 83 222 9014',
    email: 'johan.vdm@nashua.co.za',
    address: '77 6th Street, Linden, Randburg, 2195',
    medicalAidName: 'Bonitas',
    medicalAidNumber: '492018591',
    dependantCode: '00',
    planName: 'BonComprehensive',
    savingsBalanceZAR: 820.00,
    chronicAuthorised: true,
    chronicConditions: ['Type 2 Diabetes Mellitus', 'Hypercholesterolemia'],
    allergies: [],
    emergencyContact: {
      name: 'Annatjie van der Merwe',
      relationship: 'Spouse',
      phone: '+27 83 222 9015',
    },
    tags: ['Diabetic Foot Care', 'Quarterly HbA1c'],
    registeredDate: '2022-11-10',
  },
  {
    id: 'pat-004',
    fullName: 'Fatima Patel',
    idNumber: '9804220231089',
    dob: '1998-04-22',
    gender: 'Female',
    phone: '+27 84 991 3042',
    email: 'fatima.patel@webmail.co.za',
    address: '108 Central Avenue, Fordsburg, Johannesburg, 2092',
    medicalAidName: 'Momentum Health',
    medicalAidNumber: '601928374',
    dependantCode: '01',
    planName: 'Custom Ingwe',
    savingsBalanceZAR: 3100.00,
    chronicAuthorised: false,
    chronicConditions: ['Chronic Migraine'],
    allergies: ['Codeine'],
    emergencyContact: {
      name: 'Yusuf Patel',
      relationship: 'Father',
      phone: '+27 84 991 3040',
    },
    tags: ['Telehealth Preferred'],
    registeredDate: '2024-02-01',
  },
  {
    id: 'pat-005',
    fullName: 'Andile Khumalo',
    idNumber: '0108155123081',
    dob: '2001-08-15',
    gender: 'Male',
    phone: '+27 73 881 7261',
    email: 'andile.khumalo@student.wits.ac.za',
    address: 'Braamfontein Student Residence, Johannesburg, 2001',
    medicalAidName: 'Fedhealth (Medscheme)',
    medicalAidNumber: '774819201',
    dependantCode: '02',
    planName: 'Maxima Plus',
    savingsBalanceZAR: 5400.00,
    chronicAuthorised: false,
    chronicConditions: [],
    allergies: [],
    emergencyContact: {
      name: 'Nomsa Khumalo',
      relationship: 'Mother',
      phone: '+27 73 881 7260',
    },
    tags: ['Student', 'Sports Injury'],
    registeredDate: '2024-04-12',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-101',
    patientId: 'pat-001',
    patientName: 'Sipho Zulu',
    patientPhone: '+27 82 555 0192',
    medicalAidName: 'Discovery Health',
    date: new Date().toISOString().slice(0, 10),
    time: '08:30',
    durationMinutes: 30,
    type: 'Follow-up',
    status: 'In Consultation',
    triageLevel: 'Moderate',
    notes: 'Hypertension review & blood pressure check. Requests chronic prescription renewal.',
    whatsappReminderSent: true,
  },
  {
    id: 'apt-102',
    patientId: 'pat-002',
    patientName: 'Lerato Mokoena',
    patientPhone: '+27 71 444 8821',
    medicalAidName: 'GEMS',
    date: new Date().toISOString().slice(0, 10),
    time: '09:15',
    durationMinutes: 30,
    type: 'General Consultation',
    status: 'Arrived',
    triageLevel: 'Urgent',
    notes: 'Acute wheezing and nocturnal dyspnoea since cold front. Inhaled salbutamol only partially responsive.',
    whatsappReminderSent: true,
  },
  {
    id: 'apt-103',
    patientId: 'pat-003',
    patientName: 'Johan van der Merwe',
    patientPhone: '+27 83 222 9014',
    medicalAidName: 'Bonitas',
    date: new Date().toISOString().slice(0, 10),
    time: '10:00',
    durationMinutes: 30,
    type: 'Chronic Review',
    status: 'Confirmed',
    triageLevel: 'Routine',
    notes: 'Quarterly HbA1c review and diabetic peripheral foot sensory assessment.',
    whatsappReminderSent: true,
  },
  {
    id: 'apt-104',
    patientId: 'pat-004',
    patientName: 'Fatima Patel',
    patientPhone: '+27 84 991 3042',
    medicalAidName: 'Momentum Health',
    date: new Date().toISOString().slice(0, 10),
    time: '11:15',
    durationMinutes: 20,
    type: 'Telehealth',
    status: 'Confirmed',
    triageLevel: 'Routine',
    notes: 'Remote video consult for migraine prophylaxis review and digital sick certificate request.',
    whatsappReminderSent: true,
  },
  {
    id: 'apt-105',
    patientId: 'pat-005',
    patientName: 'Andile Khumalo',
    patientPhone: '+27 73 881 7261',
    medicalAidName: 'Fedhealth (Medscheme)',
    date: new Date().toISOString().slice(0, 10),
    time: '14:00',
    durationMinutes: 30,
    type: 'Procedure',
    status: 'Confirmed',
    triageLevel: 'Moderate',
    notes: 'Right knee joint aspiration / cortisone injection post rugby training injury.',
    whatsappReminderSent: false,
    isLocumCovered: true,
    locumDoctorName: 'Dr. Kgomotso Dlamini (Locum GP)',
  },
];

export const COMMON_ICD10: ICD10Code[] = [
  { code: 'I10', description: 'Essential (primary) hypertension (PMB CDL)', isPrimary: true },
  { code: 'E11.9', description: 'Type 2 diabetes mellitus without complications (PMB CDL)', isPrimary: true },
  { code: 'J45.9', description: 'Asthma, unspecified (PMB CDL)', isPrimary: true },
  { code: 'J06.9', description: 'Acute upper respiratory infection, unspecified', isPrimary: true },
  { code: 'J20.9', description: 'Acute bronchitis, unspecified', isPrimary: true },
  { code: 'M54.5', description: 'Low back pain', isPrimary: true },
  { code: 'K21.9', description: 'Gastro-oesophageal reflux disease without oesophagitis', isPrimary: true },
  { code: 'M10.9', description: 'Gout, unspecified', isPrimary: true },
  { code: 'R51', description: 'Headache, unspecified', isPrimary: false },
  { code: 'L20.9', description: 'Atopic dermatitis, unspecified', isPrimary: false },
  { code: 'U07.1', description: 'COVID-19, virus identified', isPrimary: false },
  { code: 'Z00.0', description: 'General medical examination / health checkup', isPrimary: true },
];

export const COMMON_TARIFFS: TariffItem[] = [
  { code: '0190', description: 'Consultation: Established patient in rooms (standard GP)', units: 1, rateZAR: 580.0 },
  { code: '0191', description: 'Extended consultation > 20 mins', units: 1, rateZAR: 850.0 },
  { code: '0192', description: 'Complex chronic disease consultation > 30 mins', units: 1, rateZAR: 1240.0 },
  { code: '0130', description: 'Telephonic / Telemedicine consultation', units: 1, rateZAR: 480.0 },
  { code: '0001', description: 'Point-of-care rapid diagnostics: Urine dipstick / Blood glucose', units: 1, rateZAR: 110.0 },
  { code: '0205', description: 'Intra-articular or soft tissue injection / aspiration', units: 1, rateZAR: 620.0 },
  { code: '1232', description: 'Resting 12-lead Electrocardiogram (ECG)', units: 1, rateZAR: 420.0 },
];

export const COMMON_NAPPI: NappiMedication[] = [
  {
    nappi: '702819001',
    medicineName: 'Amlodipine 5mg Tablets',
    schedule: 'S3',
    dosage: '1 tablet once daily in the morning',
    duration: '30 days',
    repeats: 5,
    quantity: 30,
    instructions: 'Take with or without food. Do not skip doses.',
  },
  {
    nappi: '715498001',
    medicineName: 'Augmentin 1000mg (Amoxicillin/Clavulanate)',
    schedule: 'S4',
    dosage: '1 tablet twice daily with meals',
    duration: '5 days',
    repeats: 0,
    quantity: 10,
    instructions: 'Complete full course even if symptoms resolve.',
  },
  {
    nappi: '761109001',
    medicineName: 'Ventolin 100mcg Inhaler (Salbutamol)',
    schedule: 'S2',
    dosage: '2 puffs 4 times daily as required for wheeze',
    duration: '1 canister',
    repeats: 3,
    quantity: 1,
    instructions: 'Rinse mouth after inhalation. Keep handy.',
  },
  {
    nappi: '721518001',
    medicineName: 'Glucophage 500mg (Metformin HCl)',
    schedule: 'S3',
    dosage: '1 tablet twice daily after meals',
    duration: '30 days',
    repeats: 5,
    quantity: 60,
    instructions: 'Take after meals to minimize gastrointestinal discomfort.',
  },
  {
    nappi: '752002001',
    medicineName: 'Panado 500mg Tablets (Paracetamol)',
    schedule: 'S0',
    dosage: '2 tablets 4 times daily PRN (max 8 tabs/24h)',
    duration: '5 days',
    repeats: 0,
    quantity: 20,
    instructions: 'Do not exceed maximum daily dosage.',
  },
  {
    nappi: '703418001',
    medicineName: 'Lipitor 20mg (Atorvastatin)',
    schedule: 'S4',
    dosage: '1 tablet at bedtime',
    duration: '30 days',
    repeats: 5,
    quantity: 30,
    instructions: 'Report any unexplained muscle pain or weakness immediately.',
  },
  {
    nappi: '718302001',
    medicineName: 'Nexiam 20mg (Esomeprazole)',
    schedule: 'S4',
    dosage: '1 tablet daily 30 minutes before breakfast',
    duration: '28 days',
    repeats: 2,
    quantity: 28,
    instructions: 'Swallow whole with a glass of water.',
  },
];

export const INITIAL_CONSULTATIONS: ClinicalConsultation[] = [
  {
    id: 'cns-201',
    appointmentId: 'apt-101',
    patientId: 'pat-001',
    patientName: 'Sipho Zulu',
    date: '2026-09-14',
    doctorName: 'Dr. Thabo Ndlovu (MBChB, FCFP)',
    vitals: {
      bp: '154/98',
      pulse: 82,
      temp: 36.8,
      spo2: 97,
      weight: 84,
      glucose: 5.8,
    },
    soapNote: {
      subjective: 'Patient reports persistent occipital morning headaches, fatigue, and bilateral toe joint stiffness. Reports missing Amlodipine doses due to travel.',
      objective: 'BP 154/98 mmHg (both arms). Heart sounds S1+S2 dual, no murmurs. Mild right 1st MTP erythema without acute podagra. Fundoscopy: mild arteriolar narrowing.',
      assessment: 'Sub-optimally controlled Essential Hypertension (PMB CDL) with hypertensive symptoms + asymptomatic hyperuricaemia.',
      plan: '1. Reinforce compliance with Amlodipine 10mg mane. 2. Low-purine dietary counselling. 3. Baseline U&E and fasting serum urate ordered. 4. Red flag review in 14 days.',
    },
    icd10Codes: [
      { code: 'I10', description: 'Essential (primary) hypertension (PMB CDL)', isPrimary: true },
      { code: 'M10.9', description: 'Gout, unspecified', isPrimary: false },
    ],
    tariffCodes: [
      { code: '0190', description: 'Consultation: Established patient in rooms', units: 1, rateZAR: 580.00 },
    ],
    prescriptions: [
      {
        nappi: '702820001',
        medicineName: 'Amlodipine 10mg Tablets (30)',
        schedule: 'S3',
        dosage: '1 tablet once daily in the morning',
        duration: '30 days',
        repeats: 5,
        quantity: 30,
        instructions: 'Take consistently every morning.',
      },
    ],
    followUpDays: 14,
    isPMB: true,
  },
  {
    id: 'cns-202',
    appointmentId: 'apt-102',
    patientId: 'pat-002',
    patientName: 'Lerato Mokoena',
    date: '2026-08-28',
    doctorName: 'Dr. Thabo Ndlovu (MBChB, FCFP)',
    vitals: {
      bp: '122/76',
      pulse: 88,
      temp: 37.0,
      spo2: 96,
      weight: 62,
    },
    soapNote: {
      subjective: 'Lerato presents with recurrent nighttime chest tightness and cough triggered by cold Johannesburg winter air. Uses Ventolin 3-4 times weekly. Severe allergy to Aspirin/NSAIDs.',
      objective: 'Bilateral mild expiratory wheeze over mid and lower zones. No intercostal retractions at rest. Peak flow: 340 L/min (predicted 420 L/min).',
      assessment: 'Partially controlled moderate persistent Bronchial Asthma (PMB CDL). Needs stepping up to inhaled corticosteroid/LABA combo.',
      plan: '1. Step-up to Symbicort Rapihaler 160/4.5mcg 2 puffs BD. 2. Written Asthma Action Plan provided. 3. STRICT avoidance of Aspirin and NSAIDs.',
    },
    icd10Codes: [
      { code: 'J45.9', description: 'Asthma, unspecified (PMB CDL)', isPrimary: true },
    ],
    tariffCodes: [
      { code: '0191', description: 'Consultation: Extended evaluation > 20 mins', units: 1, rateZAR: 850.00 },
    ],
    prescriptions: [
      {
        nappi: '761109001',
        medicineName: 'Ventolin 100mcg Inhaler',
        schedule: 'S2',
        dosage: '2 puffs PRN for acute wheezing',
        duration: '1 canister',
        repeats: 3,
        quantity: 1,
        instructions: 'Emergency rescue inhaler only.',
      },
    ],
    followUpDays: 30,
    isPMB: true,
  },
  {
    id: 'cns-203',
    appointmentId: 'apt-103',
    patientId: 'pat-003',
    patientName: 'Johan van der Merwe',
    date: '2026-06-15',
    doctorName: 'Dr. Thabo Ndlovu (MBChB, FCFP)',
    vitals: {
      bp: '136/84',
      pulse: 74,
      temp: 36.6,
      spo2: 98,
      weight: 96,
      glucose: 8.4,
    },
    soapNote: {
      subjective: 'Routine 3-month diabetes follow up. No polyuria, polydipsia, or peripheral paraesthesia. Compliant with Metformin 850mg BD.',
      objective: 'BP 136/84 mmHg. 10g Semmes-Weinstein monofilament sensation intact in both feet. Dorsalis pedis pulses palpable bilaterally. Point-of-care glucose 8.4 mmol/L.',
      assessment: 'Type 2 Diabetes Mellitus (PMB CDL) - moderate glycemic control. Last HbA1c 7.6%.',
      plan: '1. Continue Metformin. 2. Repeat fasting HbA1c and lipid profile at Lancet. 3. Annual podiatry referral booked.',
    },
    icd10Codes: [
      { code: 'E11.9', description: 'Type 2 diabetes mellitus without complications', isPrimary: true },
    ],
    tariffCodes: [
      { code: '0190', description: 'Consultation: Established patient in rooms', units: 1, rateZAR: 580.00 },
    ],
    prescriptions: [
      {
        nappi: '721518001',
        medicineName: 'Glucophage 500mg (Metformin HCl)',
        schedule: 'S3',
        dosage: '1 tablet twice daily after meals',
        duration: '30 days',
        repeats: 5,
        quantity: 60,
        instructions: 'Take after meals.',
      },
    ],
    followUpDays: 90,
    isPMB: true,
  },
];

export const INITIAL_CLAIMS: MedicalAidClaim[] = [
  {
    id: 'clm-301',
    claimRef: 'HB-CLM-901842',
    patientId: 'pat-001',
    patientName: 'Sipho Zulu',
    schemeCode: 'DISCOVERY',
    schemeName: 'Discovery Health',
    membershipNumber: '902184729',
    dependantCode: '00',
    serviceDate: '2026-09-27',
    submissionDate: '2026-09-27 10:14:02',
    totalClaimZAR: 690.00,
    paidZAR: 690.00,
    coPayZAR: 0.00,
    switchStatus: 'ADJUDICATED_PAID',
    switchTransactionId: 'HB-EDI-84910294',
    batchNumber: 'BTH-20260927-01',
    items: [
      { type: 'TARIFF', code: '0190', description: 'General Consultation', amountZAR: 580.00, paidZAR: 580.00, status: 'ACCEPTED' },
      { type: 'TARIFF', code: '0001', description: 'In-rooms point-of-care test', amountZAR: 110.00, paidZAR: 110.00, status: 'ACCEPTED' },
    ],
  },
  {
    id: 'clm-302',
    claimRef: 'HB-CLM-901843',
    patientId: 'pat-002',
    patientName: 'Lerato Mokoena',
    schemeCode: 'GEMS',
    schemeName: 'GEMS (Metropolitan Health)',
    membershipNumber: '800319482',
    dependantCode: '00',
    serviceDate: '2026-09-26',
    submissionDate: '2026-09-26 14:22:18',
    totalClaimZAR: 850.00,
    paidZAR: 722.50,
    coPayZAR: 127.50,
    switchStatus: 'PARTIALLY_PAID',
    rejectionCode: '44',
    rejectionReason: '15% co-payment applied as per member plan rules for out-of-network provider',
    switchTransactionId: 'HB-EDI-77192841',
    batchNumber: 'BTH-20260926-02',
    items: [
      { type: 'TARIFF', code: '0191', description: 'Extended Consultation > 20 mins', amountZAR: 850.00, paidZAR: 722.50, status: 'COPAY' },
    ],
  },
  {
    id: 'clm-303',
    claimRef: 'HB-CLM-901844',
    patientId: 'pat-003',
    patientName: 'Johan van der Merwe',
    schemeCode: 'BONITAS',
    schemeName: 'Bonitas Medical Fund',
    membershipNumber: '492018591',
    dependantCode: '00',
    serviceDate: '2026-09-25',
    submissionDate: '2026-09-25 11:05:40',
    totalClaimZAR: 1240.00,
    paidZAR: 1240.00,
    coPayZAR: 0.00,
    switchStatus: 'ADJUDICATED_PAID',
    switchTransactionId: 'HB-EDI-66192839',
    batchNumber: 'BTH-20260925-01',
    items: [
      { type: 'TARIFF', code: '0192', description: 'Complex Chronic Consultation', amountZAR: 1240.00, paidZAR: 1240.00, status: 'ACCEPTED' },
    ],
  },
];

export const INITIAL_REFERRALS: SpecialistReferral[] = [
  {
    id: 'ref-401',
    patientId: 'pat-001',
    patientName: 'Sipho Zulu',
    patientIdNumber: '8503145890082',
    specialistType: 'Cardiologist',
    doctorName: 'Dr. Kevin Moodley (Cardiologist)',
    hospital: 'Netcare Rosebank Hospital, Room 302',
    urgency: 'Routine (Within 2 weeks)',
    reason: 'Resistant Stage 2 Hypertension & Echocardiogram evaluation',
    clinicalSummary: 'Known hypertensive x 4 years on dual therapy. Recent ambulatory BP monitoring shows persistent nocturnal dipping loss. ECG demonstrates early LVH.',
    investigationsSummary: 'U&E normal, eGFR 84 ml/min, Resting 12-lead ECG: Sokolow-Lyon criteria positive for LVH.',
    motivationLetter: 'Formal referral requesting transthoracic echocardiography, 24-hr Holter monitor, and optimization of anti-hypertensive regimen under Discovery PMB basket.',
    dateCreated: '2026-09-26',
    status: 'Sent via Switch',
  },
  {
    id: 'ref-402',
    patientId: 'pat-005',
    patientName: 'Andile Khumalo',
    patientIdNumber: '0108155123081',
    specialistType: 'Orthopaedic Surgeon',
    doctorName: 'Dr. Sarah Van Zyl (Orthopaedics)',
    hospital: 'Wits Donald Gordon Medical Centre',
    urgency: 'Urgent (Within 48h)',
    reason: 'Suspected Right Medial Meniscus Tear & ACL Strain',
    clinicalSummary: 'Twisting injury to right knee during Varsity Cup rugby match. Joint line tenderness, +ve McMurray test, joint effusion.',
    investigationsSummary: 'X-Ray Right Knee: No bony fracture. MRI Right Knee requested via Switch pre-authorization.',
    motivationLetter: 'Colleague referral for urgent arthroscopy review and surgical opinion regarding reconstructive stabilization.',
    dateCreated: '2026-09-27',
    status: 'Accepted by Specialist',
  },
];

export const INITIAL_LOCUM_SLOTS: LocumSlotRequest[] = [
  {
    id: 'loc-501',
    practiceRoom: 'Consulting Suite 2B (Rosebank)',
    date: new Date().toISOString().slice(0, 10),
    timeSlot: '14:00 - 18:00 (4 hrs)',
    hours: 4,
    ratePerHourZAR: 850.00,
    status: 'CONFIRMED',
    matchedDoctor: {
      id: 'doc-loc-01',
      name: 'Dr. Kgomotso Dlamini',
      hpcsaNumber: 'MP 0719824',
      qualification: 'MBChB (Pretoria), Dip Obst (SA)',
      rating: 4.9,
      completedShifts: 48,
      verifiedHPCSA: true,
      phone: '+27 82 901 7734',
    },
  },
  {
    id: 'loc-502',
    practiceRoom: 'Consulting Suite 1A (Rosebank)',
    date: new Date(Date.now() + 86400000 * 2).toISOString().slice(0, 10),
    timeSlot: '08:00 - 13:00 (5 hrs)',
    hours: 5,
    ratePerHourZAR: 850.00,
    status: 'AUTO_MATCHED',
    matchedDoctor: {
      id: 'doc-loc-02',
      name: 'Dr. Sean Miller',
      hpcsaNumber: 'MP 0683921',
      qualification: 'MBChB (UCT), DA (SA)',
      rating: 4.8,
      completedShifts: 62,
      verifiedHPCSA: true,
      phone: '+27 83 451 9920',
    },
  },
];

export const INITIAL_CPD: DoctorCPDCertificate[] = [
  {
    id: 'cpd-601',
    title: 'Managing Complex Type 2 Diabetes in Primary Care (2026 STG Update)',
    provider: 'SAMA (South African Medical Association)',
    category: 'Clinical Medical',
    ceuPoints: 6,
    dateCompleted: '2026-08-14',
    expiryDate: '2027-08-14',
    status: 'COMPLETED',
    certificateUrl: 'https://hpcsa-cpd.co.za/cert/SAMA-2026-8910',
  },
  {
    id: 'cpd-602',
    title: 'POPIA & Patient Confidentiality: Digital Records in SA Private Practice',
    provider: 'HPCSA Accredited / Medical Protection Society',
    category: 'Ethics, Human Rights & Medical Law',
    ceuPoints: 5,
    dateCompleted: '2026-07-22',
    expiryDate: '2027-07-22',
    status: 'COMPLETED',
    certificateUrl: 'https://hpcsa-cpd.co.za/cert/MPS-ETH-2026-4412',
  },
  {
    id: 'cpd-603',
    title: 'Cardiovascular Risk Stratification & Novel Lipoprotein Therapeutics',
    provider: 'Wits Health Consortium',
    category: 'Clinical Medical',
    ceuPoints: 4,
    dateCompleted: '2026-09-02',
    expiryDate: '2027-09-02',
    status: 'COMPLETED',
    certificateUrl: 'https://hpcsa-cpd.co.za/cert/WHC-2026-1190',
  },
  {
    id: 'cpd-604',
    title: 'AI in Clinical Diagnostics: Medical Ethics & Diagnostic Liability Test Module',
    provider: 'Medscape / HPCSA Digital Health Portal',
    category: 'Ethics, Human Rights & Medical Law',
    ceuPoints: 3,
    dateCompleted: '',
    expiryDate: '2026-12-31',
    status: 'AVAILABLE',
  },
];

export const INITIAL_PATIENT_REMINDERS: PatientMedicineReminder[] = [
  {
    id: 'rem-701',
    patientId: 'pat-001',
    medicineName: 'Amlodipine 5mg',
    dosage: '1 tablet',
    timeOfDay: ['08:00'],
    instructions: 'Take in the morning with a glass of water',
    repeatsRemaining: 4,
    nextRefillDate: '2026-10-14',
    takenToday: true,
    streakDays: 24,
  },
  {
    id: 'rem-702',
    patientId: 'pat-001',
    medicineName: 'Allopurinol 300mg',
    dosage: '1 tablet',
    timeOfDay: ['20:00'],
    instructions: 'Take after dinner to prevent gout attacks',
    repeatsRemaining: 4,
    nextRefillDate: '2026-10-14',
    takenToday: false,
    streakDays: 18,
  },
  {
    id: 'rem-703',
    patientId: 'pat-002',
    medicineName: 'Symbicort 160/4.5mcg Inhaler',
    dosage: '2 puffs',
    timeOfDay: ['07:30', '19:30'],
    instructions: 'Rinse mouth with water after inhalation',
    repeatsRemaining: 2,
    nextRefillDate: '2026-10-05',
    takenToday: true,
    streakDays: 41,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-801',
    timestamp: '2026-09-28 09:30:12',
    operator: 'Dr. Thabo Ndlovu (HPCSA MP0694821)',
    action: 'PATIENT_FILE_DECRYPTED',
    details: 'Decrypted EHR record for Sipho Zulu (ID 8503145890082) via AES-GCM session key',
    ipAddress: '196.25.1.14 (Rosebank Practice Network)',
    standard: 'HIPAA §164.312(b)',
    hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  },
  {
    id: 'log-802',
    timestamp: '2026-09-28 09:35:45',
    operator: 'Healthbridge Switch Bridge Service',
    action: 'EDI_CLAIM_TRANSMISSION',
    details: 'Dispatched EDI Claim batch HB-CLM-901842 to Discovery Health Switch Gateway',
    ipAddress: '197.80.200.12 (Healthbridge SA Gateway)',
    standard: 'POPIA Act 4 2013',
    hash: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
  },
  {
    id: 'log-803',
    timestamp: '2026-09-28 09:42:00',
    operator: 'Patient Portal Client (Sipho Zulu)',
    action: 'CONSENT_RECORD_VERIFIED',
    details: 'Patient acknowledged POPIA Section 18 electronic disclosure for pathology exchange',
    ipAddress: '105.186.22.90 (Vodacom Mobile Network)',
    standard: 'HPCSA Ethical Guidelines',
    hash: 'ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb',
  },
];
