export interface ICD10Validation {
  valid: boolean;
  code: string;
  description: string | null;
  category: string | null;
  error?: string;
  suggestions?: string[];
}

const ICD10_CATALOG: Record<string, { desc: string; category: string }> = {
  'A00': { desc: 'Cholera', category: 'Infectious & parasitic diseases' },
  'A01': { desc: 'Malaria', category: 'Infectious & parasitic diseases' },
  'A09': { desc: 'Infectious gastroenteritis & colitis', category: 'Infectious & parasitic diseases' },
  'A15': { desc: 'Tuberculosis of respiratory organs', category: 'Tuberculosis' },
  'A16': { desc: 'Tuberculosis of other organs', category: 'Tuberculosis' },
  'A24': { desc: 'Typhoid & paratyphoid fevers', category: 'Infectious & parasitic diseases' },
  'A50': { desc: 'Sexually transmitted viral hepatitis', category: 'STI' },
  'A51': { desc: 'Syphilis', category: 'STI' },
  'A52': { desc: 'Gonococcal infection', category: 'STI' },
  'A53': { desc: 'Other sexually transmitted diseases', category: 'STI' },
  'A59': { desc: 'Genital herpetic virus infection', category: 'STI' },
  'A82': { desc: 'Vesicular exanthemata', category: 'Viral infections' },
  'B00': { desc: 'Herpesviral [herpes simplex] infections', category: 'Viral infections' },
  'B01': { desc: 'Varicella [chickenpox]', category: 'Viral infections' },
  'B05': { desc: 'Measles', category: 'Viral infections' },
  'B34': { desc: 'Viral infection of unspecified site', category: 'Viral infections' },
  'B35': { desc: 'Influenza', category: 'Influenza & pneumonia' },
  'B49': { desc: 'Mycosis', category: 'Fungal infections' },
  'B50': { desc: 'Malaria', category: 'Parasitic diseases' },
  'B56': { desc: 'Amebiasis', category: 'Parasitic diseases' },
  'B57': { desc: 'Giardiasis & balance', category: 'Parasitic diseases' },
  'B59': { desc: 'Trichomoniasis', category: 'Parasitic diseases' },
  'B65': { desc: 'Trematodiasis', category: 'Parasitic diseases' },
  'B67': { desc: 'Helminthiasis', category: 'Parasitic diseases' },
  'C00': { desc: 'Malignant neoplasm of lip', category: 'Neoplasms' },
  'C16': { desc: 'Malignant neoplasm of stomach', category: 'Neoplasms' },
  'C18': { desc: 'Malignant neoplasm of colon', category: 'Neoplasms' },
  'C50': { desc: 'Malignant neoplasm of breast', category: 'Neoplasms' },
  'C56': { desc: 'Malignant neoplasm of prostate', category: 'Neoplasms' },
  'C57': { desc: 'Malignant neoplasm of cervix', category: 'Neoplasms' },
  'C61': { desc: 'Malignant neoplasm of thyroid', category: 'Neoplasms' },
  'C62': { desc: 'Malignant neoplasm of other sites of mouth', category: 'Neoplasms' },
  'C64': { desc: 'Malignant neoplasm of kidney', category: 'Neoplasms' },
  'C77': { desc: 'Malignant neoplasm of lymphoid tissue', category: 'Neoplasms' },
  'C79': { desc: 'Malignant neoplasm of other sites', category: 'Neoplasms' },
  'D02': { desc: 'Carcinoma in situ of bronchus & lung', category: 'Neoplasms' },
  'D03': { desc: 'Carcinoma in situ of other sites', category: 'Neoplasms' },
  'D10': { desc: 'Benign neoplasm of lip', category: 'Neoplasms' },
  'D11': { desc: 'Benign neoplasm of meninges', category: 'Neoplasms' },
  'D25': { desc: 'Benign neoplasm of subcutaneous tissue', category: 'Neoplasms' },
  'D26': { desc: 'Benign neoplasm of lip', category: 'Neoplasms' },
  'D37': { desc: 'Benign neoplasm of spleen', category: 'Neoplasms' },
  'D44': { desc: 'Neoplasm of uncertain behaviour of bronchus & lung', category: 'Neoplasms' },
  'D50': { desc: 'Pure red cell anaemias', category: 'Blood & immune disorders' },
  'D61': { desc: 'Coagulation defects', category: 'Blood & immune disorders' },
  'D62': { desc: 'Anaemia in chronic disease', category: 'Blood & immune disorders' },
  'D64': { desc: 'Other anaemias', category: 'Blood & immune disorders' },
  'E03': { desc: 'Non-autoimmune hypothyroidism', category: 'Endocrine disorders' },
  'E05': { desc: 'Toxic diffuse goitre', category: 'Endocrine disorders' },
  'E08': { desc: 'Diabetes mellitus due to external causes', category: 'Endocrine disorders' },
  'E10': { desc: 'Type 1 diabetes mellitus', category: 'Endocrine disorders' },
  'E11': { desc: 'Type 2 diabetes mellitus', category: 'Endocrine disorders' },
  'E20': { desc: 'Hypoglycaemia', category: 'Endocrine disorders' },
  'E24': { desc: 'Hyperlipidaemia', category: 'Endocrine disorders' },
  'E27': { desc: 'Adrenal gland disorders', category: 'Endocrine disorders' },
  'E34': { desc: 'Hypopituitarism', category: 'Endocrine disorders' },
  'E41': { desc: 'Protein-calorie malnutrition', category: 'Nutritional disorders' },
  'E53': { desc: 'Vitamin A deficiency', category: 'Nutritional disorders' },
  'E56': { desc: 'Iron deficiency anaemia', category: 'Nutritional disorders' },
  'E65': { desc: 'Morbid obesity', category: 'Nutritional disorders' },
  'E66': { desc: 'Obesity', category: 'Nutritional disorders' },
  'F03': { desc: 'Dementia in Alzheimer disease', category: 'Mental & behavioural' },
  'F06': { desc: 'Dementia in other diseases', category: 'Mental & behavioural' },
  'F07': { desc: 'Other organic mental disorders', category: 'Mental & behavioural' },
  'F20': { desc: 'Schizophrenia', category: 'Mental & behavioural' },
  'F22': { desc: 'Delusional disorders', category: 'Mental & behavioural' },
  'F25': { desc: 'Manic episode', category: 'Mental & behavioural' },
  'F31': { desc: 'Bipolar affective disorder', category: 'Mental & behavioural' },
  'F32': { desc: 'Depressive episode', category: 'Mental & behavioural' },
  'F33': { desc: 'Recurrent depressive disorder', category: 'Mental & behavioural' },
  'F40': { desc: 'Phobic anxiety disorders', category: 'Mental & behavioural' },
  'F41': { desc: 'Other anxiety disorders', category: 'Mental & behavioural' },
  'F42': { desc: 'Obsessive-compulsive disorder', category: 'Mental & behavioural' },
  'F43': { desc: 'Reaction to severe stress & adjustment disorders', category: 'Mental & behavioural' },
  'F45': { desc: 'Somatoform disorders', category: 'Mental & behavioural' },
  'F48': { desc: 'Dissociative & conversion disorders', category: 'Mental & behavioural' },
  'F50': { desc: 'Eating disorders', category: 'Mental & behavioural' },
  'F51': { desc: 'Non-organic sleep disorders', category: 'Mental & behavioural' },
  'F53': { desc: 'Postpartum mental disorders', category: 'Mental & behavioural' },
  'F60': { desc: 'Personality disorders', category: 'Mental & behavioural' },
  'F63': { desc: 'Puerperal psychosis', category: 'Mental & behavioural' },
  'F65': { desc: 'Gender identity disorders', category: 'Mental & behavioural' },
  'F66': { desc: 'Sexual dysfunctions', category: 'Mental & behavioural' },
  'F67': { desc: 'Other disorders of sexual development', category: 'Mental & behavioural' },
  'F68': { desc: 'Other behavioural & emotional disorders', category: 'Mental & behavioural' },
  'F70': { desc: 'Mental retardation due to known biological causes', category: 'Mental & behavioural' },
  'F72': { desc: 'Moderate mental retardation', category: 'Mental & behavioural' },
  'F73': { desc: 'Mild mental retardation', category: 'Mental & behavioural' },
  'F80': { desc: 'Expressive speech & language disorders', category: 'Mental & behavioural' },
  'F81': { desc: 'Developmental speech & language disorders', category: 'Mental & behavioural' },
  'F84': { desc: 'Pervasive developmental disorders', category: 'Mental & behavioural' },
  'F88': { desc: 'Other disorders of psychological development', category: 'Mental & behavioural' },
  'F90': { desc: 'Disorders of conduct', category: 'Mental & behavioural' },
  'F91': { desc: 'Emotional disorders of childhood', category: 'Mental & behavioural' },
  'F93': { desc: 'Stuttering & related disorders', category: 'Mental & behavioural' },
  'F94': { desc: 'Stress-related specific phobias', category: 'Mental & behavioural' },
  'F95': { desc: 'Tic disorders', category: 'Mental & behavioural' },
  'F98': { desc: 'Other behavioural & emotional disorders', category: 'Mental & behavioural' },
  'G09': { desc: 'Noninfectious meningitis', category: 'Nervous system' },
  'G11': { desc: 'Peripheral neuropathies', category: 'Nervous system' },
  'G25': { desc: 'Other disorders of spinal cord', category: 'Nervous system' },
  'G30': { desc: 'Parkinson disease', category: 'Nervous system' },
  'G31': { desc: 'Hereditary degenerative disorders', category: 'Nervous system' },
  'G35': { desc: 'Multiple sclerosis', category: 'Nervous system' },
  'G37': { desc: 'Other degenerative nervous system disorders', category: 'Nervous system' },
  'G40': { desc: 'Epilepsy & recurrent seizures', category: 'Nervous system' },
  'G43': { desc: 'Migraine', category: 'Nervous system' },
  'G44': { desc: 'Headache syndromes', category: 'Nervous system' },
  'G45': { desc: 'Transient cerebral ischaemia', category: 'Nervous system' },
  'G46': { desc: 'Circulatory disorders of brain', category: 'Nervous system' },
  'G47': { desc: 'Sleep-wake disorders', category: 'Nervous system' },
  'G48': { desc: 'Other syndromes of the nervous system', category: 'Nervous system' },
  'G49': { desc: 'Sleep apnoea', category: 'Nervous system' },
  'G50': { desc: 'Brachial plexus disorders', category: 'Nervous system' },
  'G51': { desc: 'Other cranial nerve disorders', category: 'Nervous system' },
  'G53': { desc: 'Intracranial & spinal nerve disorders', category: 'Nervous system' },
  'G54': { desc: 'Neuritis & neuralgia', category: 'Nervous system' },
  'G55': { desc: 'Other peripheral nervous system disorders', category: 'Nervous system' },
  'G80': { desc: 'Cerebral palsy', category: 'Nervous system' },
  'G81': { desc: 'Paralysis of other types', category: 'Nervous system' },
  'G83': { desc: 'Paralysis, not elsewhere classified', category: 'Nervous system' },
  'G93': { desc: 'Other disorders of central nervous system', category: 'Nervous system' },
  'G96': { desc: 'Disorders of autonomic nervous system', category: 'Nervous system' },
  'H00': { desc: 'External disease of eye', category: 'Eye & ear' },
  'H10': { desc: 'Blepharoptosis & disorders of eyelid', category: 'Eye & ear' },
  'H16': { desc: 'Conjunctivitis', category: 'Eye & ear' },
  'H20': { desc: 'Disorders of iris & ciliary body', category: 'Eye & ear' },
  'H25': { desc: 'Cataract', category: 'Eye & ear' },
  'H26': { desc: 'Disorders of lens', category: 'Eye & ear' },
  'H35': { desc: 'Choroidal & retinal disorders', category: 'Eye & ear' },
  'H40': { desc: 'Glaucoma', category: 'Eye & ear' },
  'H42': { desc: 'Disorders of optic nerve', category: 'Eye & ear' },
  'H43': { desc: 'Visual field defects', category: 'Eye & ear' },
  'H44': { desc: 'Amblyopia & other vision disorders', category: 'Eye & ear' },
  'H50': { desc: 'Diplopia & strabismus', category: 'Eye & ear' },
  'H51': { desc: 'Other disorders of ocular muscle', category: 'Eye & ear' },
  'H53': { desc: 'Visual acuity disorders', category: 'Eye & ear' },
  'H59': { desc: 'Other disorders of eye', category: 'Eye & ear' },
  'H65': { desc: 'Chronic otitis media', category: 'Eye & ear' },
  'H66': { desc: 'Other disorders of middle ear', category: 'Eye & ear' },
  'H70': { desc: 'Otosclerosis', category: 'Eye & ear' },
  'H71': { desc: 'Other conductive hearing loss', category: 'Eye & ear' },
  'H72': { desc: 'Otologic conditions', category: 'Eye & ear' },
  'H81': { desc: 'Diseases of labyrinth', category: 'Eye & ear' },
  'H90': { desc: 'Unilateral sensorineural hearing loss', category: 'Eye & ear' },
  'H91': { desc: 'Bilateral sensorineural hearing loss', category: 'Eye & ear' },
  'H93': { desc: 'Other disorders of ear', category: 'Eye & ear' },
  'I00': { desc: 'Acute rheumatic fever', category: 'Diseases of circulatory system' },
  'I05': { desc: 'Rheumatic mitral valve disorders', category: 'Diseases of circulatory system' },
  'I09': { desc: 'Other rheumatic heart disease', category: 'Diseases of circulatory system' },
  'I10': { desc: 'Essential (primary) hypertension', category: 'Diseases of circulatory system' },
  'I11': { desc: 'Hypertensive heart disease', category: 'Diseases of circulatory system' },
  'I12': { desc: 'Hypertensive chronic kidney disease', category: 'Diseases of circulatory system' },
  'I13': { desc: 'Hypertensive heart & kidney disease', category: 'Diseases of circulatory system' },
  'I15': { desc: 'Other secondary hypertension', category: 'Diseases of circulatory system' },
  'I20': { desc: 'Angina pectoris', category: 'Diseases of circulatory system' },
  'I21': { desc: 'Acute myocardial infarction', category: 'Diseases of circulatory system' },
  'I25': { desc: 'Chronic ischaemic heart disease', category: 'Diseases of circulatory system' },
  'I27': { desc: 'Pulmonary heart disease', category: 'Diseases of circulatory system' },
  'I30': { desc: 'Acute pericarditis', category: 'Diseases of circulatory system' },
  'I33': { desc: 'Hypertrophic cardiomyopathy', category: 'Diseases of circulatory system' },
  'I34': { desc: 'Valvular aortic disorders', category: 'Diseases of circulatory system' },
  'I35': { desc: 'Other valvular heart disease', category: 'Diseases of circulatory system' },
  'I39': { desc: 'Other nonrheumatic heart disease', category: 'Diseases of circulatory system' },
  'I40': { desc: 'Acute myocarditis', category: 'Diseases of circulatory system' },
  'I42': { desc: 'Cardiomyopathies', category: 'Diseases of circulatory system' },
  'I44': { desc: 'Conduction disorders', category: 'Diseases of circulatory system' },
  'I46': { desc: 'Cardiac arrest', category: 'Diseases of circulatory system' },
  'I47': { desc: 'Cardiac arrhythmias', category: 'Diseases of circulatory system' },
  'I48': { desc: 'Cardiac flutter & fibrillation', category: 'Diseases of circulatory system' },
  'I49': { desc: 'Other & unspecified cardiac arrhythmia', category: 'Diseases of circulatory system' },
  'I50': { desc: 'Heart failure', category: 'Diseases of circulatory system' },
  'I51': { desc: 'Pericardial & endocardial disorders', category: 'Diseases of circulatory system' },
  'I52': { desc: 'Coronary artery disorders', category: 'Diseases of circulatory system' },
  'I53': { desc: 'Silent myocardial infarction', category: 'Diseases of circulatory system' },
  'I60': { desc: 'Subarachnoid haemorrhage', category: 'Diseases of circulatory system' },
  'I61': { desc: 'Intracerebral haemorrhage', category: 'Diseases of circulatory system' },
  'I63': { desc: 'Cerebral infarction', category: 'Diseases of circulatory system' },
  'I64': { desc: 'Stroke, unspecified', category: 'Diseases of circulatory system' },
  'I65': { desc: 'Cerebral artery disorders', category: 'Diseases of circulatory system' },
  'I66': { desc: 'Nontraumatic intracranial haemorrhage', category: 'Diseases of circulatory system' },
  'I67': { desc: 'Circulatory disorders of head & neck', category: 'Diseases of circulatory system' },
  'I70': { desc: 'Atherosclerosis', category: 'Diseases of circulatory system' },
  'I71': { desc: 'Arterial disorders', category: 'Diseases of circulatory system' },
  'I72': { desc: 'Arteritis & arteriosclerosis', category: 'Diseases of circulatory system' },
  'I73': { desc: 'Other disorders of arteries', category: 'Diseases of circulatory system' },
  'I77': { desc: 'Phlebitis & thrombophlebitis', category: 'Diseases of circulatory system' },
  'I78': { desc: 'Portal & other venous hypertension', category: 'Diseases of circulatory system' },
  'I79': { desc: 'Other disorders of veins', category: 'Diseases of circulatory system' },
  'I80': { desc: 'Phlebitis & thrombophlebitis of lower limb', category: 'Diseases of circulatory system' },
  'I82': { desc: 'Thrombosis & embolism of pelvic veins', category: 'Diseases of circulatory system' },
  'I83': { desc: 'Thrombosis of iliac & femoral veins', category: 'Diseases of circulatory system' },
  'I95': { desc: 'Drug-induced hypotension', category: 'Diseases of circulatory system' },
  'J00': { desc: 'Influenza with pneumonia', category: 'Respiratory system' },
  'J01': { desc: 'Influenza with other respiratory manifestations', category: 'Respiratory system' },
  'J02': { desc: 'Acute pharyngitis & laryngitis', category: 'Respiratory system' },
  'J03': { desc: 'Tonsillitis & pharyngitis', category: 'Respiratory system' },
  'J04': { desc: 'Acute laryngitis & tracheitis', category: 'Respiratory system' },
  'J05': { desc: 'Acute upper respiratory infections', category: 'Respiratory system' },
  'J06': { desc: 'Acute upper respiratory infection, unspecified', category: 'Respiratory system' },
  'J08': { desc: 'Acute lower respiratory infections', category: 'Respiratory system' },
  'J09': { desc: 'Influenza due to identified virus', category: 'Respiratory system' },
  'J10': { desc: 'Influenza due to other viruses', category: 'Respiratory system' },
  'J11': { desc: 'Influenza, virus unidentified', category: 'Respiratory system' },
  'J12': { desc: 'Viral pneumonia', category: 'Respiratory system' },
  'J13': { desc: 'Pneumococcal pneumonia', category: 'Respiratory system' },
  'J14': { desc: 'Pneumonia due to other organisms', category: 'Respiratory system' },
  'J15': { desc: 'Bacterial pneumonia', category: 'Respiratory system' },
  'J16': { desc: 'Pneumonia, organism unspecified', category: 'Respiratory system' },
  'J17': { desc: 'Pneumonia due to mixed organisms', category: 'Respiratory system' },
  'J18': { desc: 'Other pneumonia', category: 'Respiratory system' },
  'J20': { desc: 'Acute bronchitis', category: 'Respiratory system' },
  'J21': { desc: 'Acute respiratory infections', category: 'Respiratory system' },
  'J22': { desc: 'Unspecified chronic lower respiratory infection', category: 'Respiratory system' },
  'J30': { desc: 'Noninfectious rhinitis', category: 'Respiratory system' },
  'J31': { desc: 'Chronic sinusitis', category: 'Respiratory system' },
  'J32': { desc: 'Chronic laryngitis & pharyngitis', category: 'Respiratory system' },
  'J33': { desc: 'Nasal polyp', category: 'Respiratory system' },
  'J34': { desc: 'Chronic sinusitis & upper airway disorders', category: 'Respiratory system' },
  'J35': { desc: 'Chronic sinusitis', category: 'Respiratory system' },
  'J36': { desc: 'Other chronic noninfectious disorders of upper respiratory tract', category: 'Respiratory system' },
  'J37': { desc: 'Chronic laryngitis & pharyngitis', category: 'Respiratory system' },
  'J38': { desc: 'Haemorrhage & other disorders of upper respiratory tract', category: 'Respiratory system' },
  'J39': { desc: 'Other disorders of upper respiratory tract', category: 'Respiratory system' },
  'J40': { desc: 'Chronic obstructive pulmonary disease', category: 'Respiratory system' },
  'J41': { desc: 'Emphysema', category: 'Respiratory system' },
  'J42': { desc: 'Bronchiectasis', category: 'Respiratory system' },
  'J43': { desc: 'Asthma, unspecified', category: 'Respiratory system' },
  'J44': { desc: 'Other chronic obstructive pulmonary disease', category: 'Respiratory system' },
  'J45': { desc: 'Asthma', category: 'Respiratory system' },
  'J46': { desc: 'Status asthmaticus', category: 'Respiratory system' },
  'J47': { desc: 'Laryngospasm & dysphonia', category: 'Respiratory system' },
  'J48': { desc: 'Pulmonary oedema', category: 'Respiratory system' },
  'J60': { desc: 'Obstructive airways disease', category: 'Respiratory system' },
  'J61': { desc: 'Exogenous alveolar proteinosis', category: 'Respiratory system' },
  'J62': { desc: 'Respiratory conditions due to inhalation of fumes', category: 'Respiratory system' },
  'J63': { desc: 'Endogenous alveolar proteinosis', category: 'Respiratory system' },
  'J64': { desc: 'Pneumonitis, unspecified', category: 'Respiratory system' },
  'J65': { desc: 'Asbestosis & other pneumoconiosis', category: 'Respiratory system' },
  'J66': { desc: 'Pneumoconiosis with tuberculosis', category: 'Respiratory system' },
  'J67': { desc: 'Other lung conditions due to external agents', category: 'Respiratory system' },
  'J68': { desc: 'Pulmonary complications in diseases classified elsewhere', category: 'Respiratory system' },
  'J69': { desc: 'Pneumonitis due to solids & liquids', category: 'Respiratory system' },
  'J70': { desc: 'Acute upper respiratory infection', category: 'Respiratory system' },
  'J71': { desc: 'Pulmonary oedema & haemorrhage', category: 'Respiratory system' },
  'J72': { desc: 'Acute respiratory distress syndrome', category: 'Respiratory system' },
  'J73': { desc: 'Pleural conditions', category: 'Respiratory system' },
  'J74': { desc: 'Intrathoracic lymph node disorders', category: 'Respiratory system' },
  'J75': { desc: 'Pulmonary aspergillosis', category: 'Respiratory system' },
  'J76': { desc: 'Extrapulmonary aspergillosis', category: 'Respiratory system' },
  'J77': { desc: 'Other mycotic respiratory infections', category: 'Respiratory system' },
  'J80': { desc: 'Bronchiolitis & bronchiolitis obliterans', category: 'Respiratory system' },
  'J81': { desc: 'Interstitial pneumonia', category: 'Respiratory system' },
  'J82': { desc: 'Exogenous alveolar proteinosis', category: 'Respiratory system' },
  'J83': { desc: 'Exogenous alveolar proteinosis', category: 'Respiratory system' },
  'J84': { desc: 'Interstitial pneumonia', category: 'Respiratory system' },
  'J85': { desc: 'Exogenous alveolar proteinosis', category: 'Respiratory system' },
  'J86': { desc: 'Lung abscess', category: 'Respiratory system' },
  'J90': { desc: 'Pleural effusion', category: 'Respiratory system' },
  'J91': { desc: 'Pleural effusion', category: 'Respiratory system' },
  'J92': { desc: 'Pleural plaques', category: 'Respiratory system' },
  'J93': { desc: 'Pneumothorax', category: 'Respiratory system' },
  'J94': { desc: 'Other pleural disorders', category: 'Respiratory system' },
  'J95': { desc: 'Pleural effusion', category: 'Respiratory system' },
  'J96': { desc: 'Respiratory failure', category: 'Respiratory system' },
  'J97': { desc: 'Other pulmonary complications', category: 'Respiratory system' },
  'J98': { desc: 'Other diseases of upper respiratory tract', category: 'Respiratory system' },
  'J99': { desc: 'Other respiratory disorders', category: 'Respiratory system' },
  'K00': { desc: 'Dental caries', category: 'Digestive system' },
  'K02': { desc: 'Noncarious dental lesions', category: 'Digestive system' },
  'K05': { desc: 'Pericoronitis', category: 'Digestive system' },
  'K06': { desc: 'Diseases of gingiva', category: 'Digestive system' },
  'K11': { desc: 'Mucous membrane disorders', category: 'Digestive system' },
  'K12': { desc: 'Retained dental materials', category: 'Digestive system' },
  'K13': { desc: 'Disorders of jaw', category: 'Digestive system' },
  'K20': { desc: 'Oesophagitis', category: 'Digestive system' },
  'K21': { desc: 'Gastro-oesophageal reflux disease', category: 'Digestive system' },
  'K22': { desc: 'Oesophageal dysfunction', category: 'Digestive system' },
  'K25': { desc: 'Peptic ulcer of stomach', category: 'Digestive system' },
  'K26': { desc: 'Peptic ulcer of duodenum', category: 'Digestive system' },
  'K27': { desc: 'Gastritis & duodenitis', category: 'Digestive system' },
  'K28': { desc: 'Peptic ulcer, unspecified', category: 'Digestive system' },
  'K29': { desc: 'Gastritis & duodenitis', category: 'Digestive system' },
  'K30': { desc: 'Hiatus hernia', category: 'Digestive system' },
  'K31': { desc: 'Hiatus hernia', category: 'Digestive system' },
  'K35': { desc: 'Acute appendicitis', category: 'Digestive system' },
  'K36': { desc: 'Other appendicitis', category: 'Digestive system' },
  'K37': { desc: 'Incarcerated & strangulated hernia', category: 'Digestive system' },
  'K38': { desc: 'Incarcerated & strangulated hernia', category: 'Digestive system' },
  'K39': { desc: 'Hernia of diaphragm', category: 'Digestive system' },
  'K40': { desc: 'Inguinal hernia', category: 'Digestive system' },
  'K41': { desc: 'Femoral hernia', category: 'Digestive system' },
  'K42': { desc: 'Ventral hernia', category: 'Digestive system' },
  'K43': { desc: 'Other & unspecified abdominal hernia', category: 'Digestive system' },
  'K46': { desc: 'Incisional hernia', category: 'Digestive system' },
  'K47': { desc: 'Morbid obesity', category: 'Digestive system' },
  'K50': { desc: "Crohn's disease", category: 'Digestive system' },
  'K51': { desc: 'Ulcerative colitis', category: 'Digestive system' },
  'K52': { desc: 'Other noninfective gastroenteritis & colitis', category: 'Digestive system' },
  'K55': { desc: 'Haemorrhagic colitis', category: 'Digestive system' },
  'K56': { desc: 'Ischaemic colitis', category: 'Digestive system' },
  'K58': { desc: 'Colonic polyp', category: 'Digestive system' },
  'K59': { desc: 'Constipation', category: 'Digestive system' },
  'K60': { desc: 'Anal fissure', category: 'Digestive system' },
  'K61': { desc: 'Anal fistula & abscess', category: 'Digestive system' },
  'K62': { desc: 'Hemorrhoids', category: 'Digestive system' },
  'K63': { desc: 'Fistula of anus & rectum', category: 'Digestive system' },
  'K65': { desc: 'Peritonitis', category: 'Digestive system' },
  'K70': { desc: 'Alcoholic liver disease', category: 'Digestive system' },
  'K71': { desc: 'Fatty liver & hepatic fibrosis', category: 'Digestive system' },
  'K72': { desc: 'Hepatic necrosis', category: 'Digestive system' },
  'K73': { desc: 'Hepatitis', category: 'Digestive system' },
  'K74': { desc: 'Fibrosis & cirrhosis of liver', category: 'Digestive system' },
  'K75': { desc: 'Other inflammatory liver diseases', category: 'Digestive system' },
  'K76': { desc: 'Other disorders of liver', category: 'Digestive system' },
  'K80': { desc: 'Cholelithiasis', category: 'Digestive system' },
  'K81': { desc: 'Cholecystitis', category: 'Digestive system' },
  'K82': { desc: 'Other biliary cysts', category: 'Digestive system' },
  'K83': { desc: 'Cholangitis & cholangiohepatitis', category: 'Digestive system' },
  'K84': { desc: 'Other inflammatory disorders of bile ducts', category: 'Digestive system' },
  'K85': { desc: 'Biliary atresia', category: 'Digestive system' },
  'K86': { desc: 'Cholangiocarcinoma', category: 'Digestive system' },
  'K87': { desc: 'Cholangiocarcinoma', category: 'Digestive system' },
  'K88': { desc: 'Cholangiocarcinoma', category: 'Digestive system' },
  'K89': { desc: 'Cholangiocarcinoma', category: 'Digestive system' },
  'K90': { desc: 'Other disorders of biliary tract', category: 'Digestive system' },
  'K91': { desc: 'Other disorders of stomach & duodenum', category: 'Digestive system' },
  'K92': { desc: 'Other disorders of intestines', category: 'Digestive system' },
  'K93': { desc: 'Other disorders of intestines', category: 'Digestive system' },
  'K94': { desc: 'Other disorders of intestines', category: 'Digestive system' },
  'K95': { desc: 'Peritonitis', category: 'Digestive system' },
  'K96': { desc: 'Other disorders of digestive system', category: 'Digestive system' },
  'L02': { desc: 'Cutaneous abscess, furuncle & carbuncle', category: 'Skin & subcutaneous tissue' },
  'L03': { desc: 'Cellulitis & fasciitis', category: 'Skin & subcutaneous tissue' },
  'L04': { desc: 'Lymphadenitis', category: 'Skin & subcutaneous tissue' },
  'L10': { desc: 'Hidradenitis suppurativa', category: 'Skin & subcutaneous tissue' },
  'L20': { desc: 'Atopic dermatitis', category: 'Skin & subcutaneous tissue' },
  'L27': { desc: 'Toxic skin reactions', category: 'Skin & subcutaneous tissue' },
  'L29': { desc: 'Urticaria', category: 'Skin & subcutaneous tissue' },
  'L30': { desc: 'Pruritus', category: 'Skin & subcutaneous tissue' },
  'L40': { desc: 'Psoriasis', category: 'Skin & subcutaneous tissue' },
  'L44': { desc: 'Pityriasis rosea', category: 'Skin & subcutaneous tissue' },
  'L54': { desc: 'Tinea pedis', category: 'Skin & subcutaneous tissue' },
  'L57': { desc: 'Dermatitis', category: 'Skin & subcutaneous tissue' },
  'L60': { desc: 'Lupus', category: 'Skin & subcutaneous tissue' },
  'L61': { desc: 'Hidradenitis suppurativa', category: 'Skin & subcutaneous tissue' },
  'L62': { desc: 'Acne', category: 'Skin & subcutaneous tissue' },
  'L70': { desc: 'Molluscum contagiosum', category: 'Skin & subcutaneous tissue' },
  'L71': { desc: 'Papilloma', category: 'Skin & subcutaneous tissue' },
  'L72': { desc: 'Seborrhoeic dermatitis', category: 'Skin & subcutaneous tissue' },
  'L73': { desc: 'Warts', category: 'Skin & subcutaneous tissue' },
  'L80': { desc: 'Mite bite', category: 'Skin & subcutaneous tissue' },
  'L81': { desc: 'Lice', category: 'Skin & subcutaneous tissue' },
  'L82': { desc: 'Fleas', category: 'Skin & subcutaneous tissue' },
  'L83': { desc: 'Contact urticaria', category: 'Skin & subcutaneous tissue' },
  'L84': { desc: 'Contusion', category: 'Skin & subcutaneous tissue' },
  'L85': { desc: 'Other local infections', category: 'Skin & subcutaneous tissue' },
  'L86': { desc: 'Insect bite', category: 'Skin & subcutaneous tissue' },
  'L87': { desc: 'Nail disorders', category: 'Skin & subcutaneous tissue' },
  'L88': { desc: 'Scabies', category: 'Skin & subcutaneous tissue' },
  'L89': { desc: 'Pressure ulcer', category: 'Skin & subcutaneous tissue' },
  'L90': { desc: 'Dermatitis', category: 'Skin & subcutaneous tissue' },
  'L91': { desc: 'Pemphigus', category: 'Skin & subcutaneous tissue' },
  'L92': { desc: 'Pemphigoid', category: 'Skin & subcutaneous tissue' },
  'L93': { desc: 'Vesiculobullous diseases', category: 'Skin & subcutaneous tissue' },
  'L94': { desc: 'Lichen planus', category: 'Skin & subcutaneous tissue' },
  'L95': { desc: 'Porphyria', category: 'Skin & subcutaneous tissue' },
  'L96': { desc: 'Scleroderma', category: 'Skin & subcutaneous tissue' },
  'L97': { desc: 'Venous insufficiency', category: 'Skin & subcutaneous tissue' },
  'L98': { desc: 'Pyoderma', category: 'Skin & subcutaneous tissue' },
  'L99': { desc: 'Other disorders of skin', category: 'Skin & subcutaneous tissue' },
  'M05': { desc: 'Rheumatoid arthritis', category: 'Musculoskeletal system' },
  'M06': { desc: 'Crystal arthropathies', category: 'Musculoskeletal system' },
  'M07': { desc: 'Inflammatory polyarthropathies', category: 'Musculoskeletal system' },
  'M09': { desc: 'Enthesopathies', category: 'Musculoskeletal system' },
  'M10': { desc: 'Gout & related arthropathies', category: 'Musculoskeletal system' },
  'M11': { desc: 'Other crystal arthropathies', category: 'Musculoskeletal system' },
  'M13': { desc: 'Other arthropathies', category: 'Musculoskeletal system' },
  'M17': { desc: 'Osteoarthritis of hip', category: 'Musculoskeletal system' },
  'M18': { desc: 'Osteoarthritis of knee', category: 'Musculoskeletal system' },
  'M19': { desc: 'Other osteoarthritis', category: 'Musculoskeletal system' },
  'M20': { desc: 'Carpal tunnel syndrome', category: 'Musculoskeletal system' },
  'M21': { desc: 'Acquired deformities', category: 'Musculoskeletal system' },
  'M25': { desc: 'Other joint disorders', category: 'Musculoskeletal system' },
  'M30': { desc: 'Diffuse scleroderma', category: 'Musculoskeletal system' },
  'M31': { desc: 'Systemic scleroderma', category: 'Musculoskeletal system' },
  'M32': { desc: 'Systemic lupus erythematosus', category: 'Musculoskeletal system' },
  'M33': { desc: 'Mycositis', category: 'Musculoskeletal system' },
  'M34': { desc: 'Reiter syndrome', category: 'Musculoskeletal system' },
  'M35': { desc: 'Vasculitis', category: 'Musculoskeletal system' },
  'M36': { desc: 'Other connective tissue disorders', category: 'Musculoskeletal system' },
  'M40': { desc: 'Kyphosis & scoliosis', category: 'Musculoskeletal system' },
  'M42': { desc: 'Osteoporosis', category: 'Musculoskeletal system' },
  'M45': { desc: 'Spinal stenosis', category: 'Musculoskeletal system' },
  'M46': { desc: 'Spondylopathies', category: 'Musculoskeletal system' },
  'M47': { desc: 'Meningitis', category: 'Musculoskeletal system' },
  'M48': { desc: 'Ankylosing spondylitis', category: 'Musculoskeletal system' },
  'M49': { desc: 'Other dorsopathies', category: 'Musculoskeletal system' },
  'M50': { desc: 'Cervical disc disorders', category: 'Musculoskeletal system' },
  'M51': { desc: 'Lumbar disc disorders', category: 'Musculoskeletal system' },
  'M53': { desc: 'Other noninfective dorsopathies', category: 'Musculoskeletal system' },
  'M54': { desc: 'Low back pain', category: 'Musculoskeletal system' },
  'M55': { desc: 'Disorders of intervertebral disc', category: 'Musculoskeletal system' },
  'M56': { desc: 'Spondylosis & disc degeneration', category: 'Musculoskeletal system' },
  'M57': { desc: 'Arthropathy of sacroiliac joint', category: 'Musculoskeletal system' },
  'M58': { desc: 'Arthropathy of sacrum', category: 'Musculoskeletal system' },
  'M59': { desc: 'Other arthropathies', category: 'Musculoskeletal system' },
  'M60': { desc: 'Myositis', category: 'Musculoskeletal system' },
  'M61': { desc: 'Fibromyalgia', category: 'Musculoskeletal system' },
  'M62': { desc: 'Enthesopathies', category: 'Musculoskeletal system' },
  'M63': { desc: 'Arthralgia', category: 'Musculoskeletal system' },
  'M65': { desc: 'Tendinitis & related disorders', category: 'Musculoskeletal system' },
  'M66': { desc: 'Tendinitis of shoulder', category: 'Musculoskeletal system' },
  'M70': { desc: 'Carpal tunnel syndrome', category: 'Musculoskeletal system' },
  'M71': { desc: 'Bursitis & tenosynovitis', category: 'Musculoskeletal system' },
  'M72': { desc: 'Fascial disorders', category: 'Musculoskeletal system' },
  'M73': { desc: 'Dystrophy of muscle', category: 'Musculoskeletal system' },
  'M74': { desc: 'Bursitis & tenosynovitis', category: 'Musculoskeletal system' },
  'M75': { desc: 'Shoulder disorders', category: 'Musculoskeletal system' },
  'M76': { desc: 'Bursitis & tenosynovitis', category: 'Musculoskeletal system' },
  'M77': { desc: 'Other enthesopathies', category: 'Musculoskeletal system' },
  'M78': { desc: 'Gout of hand', category: 'Musculoskeletal system' },
  'M79': { desc: 'Other pain in muscles', category: 'Musculoskeletal system' },
  'M80': { desc: 'Osteomyelitis', category: 'Musculoskeletal system' },
  'M81': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M82': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M83': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M84': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M85': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M86': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M87': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M88': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M89': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M90': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M91': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M92': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M93': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M94': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M95': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M96': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M97': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M98': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'M99': { desc: 'Osteitis', category: 'Musculoskeletal system' },
  'N00': { desc: 'Acute glomerulonephritis', category: 'Urinary system' },
  'N03': { desc: 'Chronic glomerulonephritis', category: 'Urinary system' },
  'N04': { desc: 'Nephritic syndrome', category: 'Urinary system' },
  'N05': { desc: 'Nephrotic syndrome', category: 'Urinary system' },
  'N06': { desc: 'Unspecified glomerulonephritis', category: 'Urinary system' },
  'N07': { desc: 'Alport syndrome', category: 'Urinary system' },
  'N08': { desc: 'Other glomerular diseases', category: 'Urinary system' },
  'N09': { desc: 'Glomerular disorders', category: 'Urinary system' },
  'N10': { desc: 'Acute tubulointerstitial nephritis', category: 'Urinary system' },
  'N11': { desc: 'Chronic tubulointerstitial nephritis', category: 'Urinary system' },
  'N12': { desc: 'Renal tubular acidosis', category: 'Urinary system' },
  'N13': { desc: 'Renal lithiasis', category: 'Urinary system' },
  'N14': { desc: 'Other urinary tract infections', category: 'Urinary system' },
  'N15': { desc: 'Renal & ureteral colic', category: 'Urinary system' },
  'N16': { desc: 'Postrenal obstruction', category: 'Urinary system' },
  'N17': { desc: 'Acute kidney failure', category: 'Urinary system' },
  'N18': { desc: 'Chronic kidney failure', category: 'Urinary system' },
  'N19': { desc: 'Unspecified kidney & ureteral disorders', category: 'Urinary system' },
  'N20': { desc: 'Calculus in urinary tract', category: 'Urinary system' },
  'N21': { desc: 'Obstructive & reflux uropathy', category: 'Urinary system' },
  'N22': { desc: 'Other urinary tract obstructions', category: 'Urinary system' },
  'N23': { desc: 'Other urinary tract obstructions', category: 'Urinary system' },
  'N24': { desc: 'Other urinary tract obstructions', category: 'Urinary system' },
  'N25': { desc: 'Other urinary tract obstructions', category: 'Urinary system' },
  'N26': { desc: 'Other urinary tract obstructions', category: 'Urinary system' },
  'N27': { desc: 'Other urinary tract obstructions', category: 'Urinary system' },
  'N28': { desc: 'Other urinary tract obstructions', category: 'Urinary system' },
  'N29': { desc: 'Other urinary tract obstructions', category: 'Urinary system' },
  'N30': { desc: 'Cystitis', category: 'Urinary system' },
  'N31': { desc: 'Urinary tract infection', category: 'Urinary system' },
  'N32': { desc: 'Other urinary tract infections', category: 'Urinary system' },
  'N33': { desc: 'Other urinary tract infections', category: 'Urinary system' },
  'N34': { desc: 'Other urinary tract infections', category: 'Urinary system' },
  'N35': { desc: 'Other urinary tract infections', category: 'Urinary system' },
  'N36': { desc: 'Other urinary tract infections', category: 'Urinary system' },
  'N37': { desc: 'Other urinary tract infections', category: 'Urinary system' },
  'N38': { desc: 'Other urinary tract infections', category: 'Urinary system' },
  'N39': { desc: 'Other urinary tract infections', category: 'Urinary system' },
  'N40': { desc: 'Benign prostatic hyperplasia', category: 'Urinary system' },
  'N41': { desc: 'Prostatitis', category: 'Urinary system' },
  'N42': { desc: 'Other prostatic disorders', category: 'Urinary system' },
  'N43': { desc: 'Hydrocele & spermatocele', category: 'Urinary system' },
  'N44': { desc: 'Malignant neoplasm of prostate', category: 'Urinary system' },
  'N45': { desc: 'Malignant neoplasm of kidney', category: 'Urinary system' },
  'N46': { desc: 'Erectile dysfunction', category: 'Urinary system' },
  'N47': { desc: 'Other male genital disorders', category: 'Urinary system' },
  'N48': { desc: 'Other male genital disorders', category: 'Urinary system' },
  'N49': { desc: 'Other male genital disorders', category: 'Urinary system' },
  'N50': { desc: 'Disorders of penis', category: 'Urinary system' },
  'N51': { desc: 'Other male genital disorders', category: 'Urinary system' },
  'N52': { desc: 'Other male genital disorders', category: 'Urinary system' },
  'N53': { desc: 'Other male genital disorders', category: 'Urinary system' },
  'N54': { desc: 'Other male genital disorders', category: 'Urinary system' },
  'N55': { desc: 'Other male genital disorders', category: 'Urinary system' },
  'N56': { desc: 'Other male genital disorders', category: 'Urinary system' },
  'N57': { desc: 'Other male genital disorders', category: 'Urinary system' },
  'N58': { desc: 'Other male genital disorders', category: 'Urinary system' },
  'N59': { desc: 'Other male genital disorders', category: 'Urinary system' },
  'N60': { desc: 'Female lactational disorders', category: 'Urinary system' },
  'N61': { desc: 'Disorders of nipple & breast', category: 'Urinary system' },
  'N62': { desc: 'Amenorrhoea', category: 'Urinary system' },
  'N63': { desc: 'Enlarged breast', category: 'Urinary system' },
  'N64': { desc: 'Other disorders of breast', category: 'Urinary system' },
  'N70': { desc: 'Inflammatory disorders of female pelvis', category: 'Urinary system' },
  'N71': { desc: 'Noninflammatory disorders of cervix', category: 'Urinary system' },
  'N72': { desc: 'Disorders of uterus', category: 'Urinary system' },
  'N73': { desc: 'Disorders of uterus', category: 'Urinary system' },
  'N74': { desc: 'Disorders of uterus', category: 'Urinary system' },
  'N75': { desc: 'Disorders of uterus', category: 'Urinary system' },
  'N76': { desc: 'Disorders of uterus', category: 'Urinary system' },
  'N77': { desc: 'Disorders of uterus', category: 'Urinary system' },
  'N78': { desc: 'Disorders of uterus', category: 'Urinary system' },
  'N79': { desc: 'Disorders of uterus', category: 'Urinary system' },
  'N80': { desc: 'Adhesions of pelvis', category: 'Urinary system' },
  'N81': { desc: 'Cyst of ovary', category: 'Urinary system' },
  'N82': { desc: 'Ovarian dysfunction', category: 'Urinary system' },
  'N83': { desc: 'Ovarian dysfunction', category: 'Urinary system' },
  'N84': { desc: 'Ovarian dysfunction', category: 'Urinary system' },
  'N85': { desc: 'Ovarian dysfunction', category: 'Urinary system' },
  'N86': { desc: 'Ovarian dysfunction', category: 'Urinary system' },
  'N87': { desc: 'Ovarian dysfunction', category: 'Urinary system' },
  'N88': { desc: 'Ovarian dysfunction', category: 'Urinary system' },
  'N89': { desc: 'Ovarian dysfunction', category: 'Urinary system' },
  'N90': { desc: 'Other disorders of uterus', category: 'Urinary system' },
  'N91': { desc: 'Abnormal uterine bleeding', category: 'Urinary system' },
  'N92': { desc: 'Abnormal uterine bleeding', category: 'Urinary system' },
  'N93': { desc: 'Abnormal uterine bleeding', category: 'Urinary system' },
  'N94': { desc: 'Abnormal uterine bleeding', category: 'Urinary system' },
  'N95': { desc: 'Abnormal uterine bleeding', category: 'Urinary system' },
  'N96': { desc: 'Abnormal uterine bleeding', category: 'Urinary system' },
  'N97': { desc: 'Abnormal uterine bleeding', category: 'Urinary system' },
  'N98': { desc: 'Abnormal uterine bleeding', category: 'Urinary system' },
  'N99': { desc: 'Abnormal uterine bleeding', category: 'Urinary system' },
  'O00': { desc: 'Ectopic pregnancy', category: 'Pregnancy & childbirth' },
  'O01': { desc: 'Molar pregnancy', category: 'Pregnancy & childbirth' },
  'O02': { desc: 'Miscarriage', category: 'Pregnancy & childbirth' },
  'O03': { desc: 'Miscarriage', category: 'Pregnancy & childbirth' },
  'O04': { desc: 'Miscarriage', category: 'Pregnancy & childbirth' },
  'O05': { desc: 'Miscarriage', category: 'Pregnancy & childbirth' },
  'O06': { desc: 'Miscarriage', category: 'Pregnancy & childbirth' },
  'O07': { desc: 'Miscarriage', category: 'Pregnancy & childbirth' },
  'O08': { desc: 'Miscarriage', category: 'Pregnancy & childbirth' },
  'O09': { desc: 'Antenatal care', category: 'Pregnancy & childbirth' },
  'O10': { desc: 'Antenatal care', category: 'Pregnancy & childbirth' },
  'O11': { desc: 'Antenatal care', category: 'Pregnancy & childbirth' },
  'O12': { desc: 'Antenatal care', category: 'Pregnancy & childbirth' },
  'O13': { desc: 'Antenatal care', category: 'Pregnancy & childbirth' },
  'O14': { desc: 'Antenatal care', category: 'Pregnancy & childbirth' },
  'O15': { desc: 'Antenatal care', category: 'Pregnancy & childbirth' },
  'O16': { desc: 'Antenatal care', category: 'Pregnancy & childbirth' },
  'O17': { desc: 'Antenatal care', category: 'Pregnancy & childbirth' },
  'O18': { desc: 'Antenatal care', category: 'Pregnancy & childbirth' },
  'O19': { desc: 'Antenatal care', category: 'Pregnancy & childbirth' },
  'O20': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O21': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O22': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O23': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O24': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O25': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O26': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O27': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O28': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O29': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O30': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O31': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O32': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O33': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O34': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O35': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O36': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O37': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O38': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O39': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O40': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O41': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O42': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O43': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O44': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O45': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O46': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O47': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O48': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O49': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O50': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O51': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O52': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O53': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O54': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O55': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O56': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O57': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O58': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O59': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O60': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O61': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O62': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O63': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O64': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O65': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O66': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O67': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O68': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O69': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O70': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O71': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O72': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O73': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O74': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O75': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O76': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O77': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O78': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O79': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O80': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O81': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O82': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O83': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O84': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O85': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O86': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O87': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O88': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O89': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O90': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O91': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O92': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O93': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O94': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O95': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O96': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O97': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O98': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'O99': { desc: 'Maternal care', category: 'Pregnancy & childbirth' },
  'P00': { desc: 'Conditions of newborn', category: 'Newborn' },
  'P01': { desc: 'Conditions of newborn', category: 'Newborn' },
  'P02': { desc: 'Conditions of newborn', category: 'Newborn' },
  'P03': { desc: 'Conditions of newborn', category: 'Newborn' },
  'P04': { desc: 'Conditions of newborn', category: 'Newborn' },
  'P05': { desc: 'Conditions of newborn', category: 'Newborn' },
  'P06': { desc: 'Conditions of newborn', category: 'Newborn' },
  'P07': { desc: 'Conditions of newborn', category: 'Newborn' },
  'P08': { desc: 'Conditions of newborn', category: 'Newborn' },
  'P09': { desc: 'Conditions of newborn', category: 'Newborn' },
  'P10': { desc: 'Neonatal jaundice', category: 'Newborn' },
  'P20': { desc: 'Neonatal respiratory', category: 'Newborn' },
  'P21': { desc: 'Neonatal respiratory', category: 'Newborn' },
  'P22': { desc: 'Neonatal respiratory', category: 'Newborn' },
  'P23': { desc: 'Neonatal respiratory', category: 'Newborn' },
  'P24': { desc: 'Neonatal respiratory', category: 'Newborn' },
  'P25': { desc: 'Neonatal respiratory', category: 'Newborn' },
  'P26': { desc: 'Neonatal respiratory', category: 'Newborn' },
  'P27': { desc: 'Neonatal respiratory', category: 'Newborn' },
  'P28': { desc: 'Neonatal respiratory', category: 'Newborn' },
  'P29': { desc: 'Neonatal respiratory', category: 'Newborn' },
  'P30': { desc: 'Neonatal conditions', category: 'Newborn' },
};

const ICD10_REGEX = /^[A-Z]\d{2}(\.\d{1,4})?/;

export function validateICD10(code: string): ICD10Validation {
  const trimmed = code.trim().toUpperCase();

  if (!trimmed) {
    return { valid: false, code: trimmed, description: null, category: null, error: 'ICD-10 code is required' };
  }

  if (!ICD10_REGEX.test(trimmed)) {
    const suggestions = findSuggestions(trimmed);
    return {
      valid: false,
      code: trimmed,
      description: null,
      category: null,
      error: `Invalid ICD-10 format. Expected: letter + 2 digits (e.g. E11.9). Found: "${trimmed}"`,
      suggestions,
    };
  }

  const baseCode = trimmed.split('.')[0];
  const entry = ICD10_CATALOG[baseCode];

  if (entry) {
    return {
      valid: true,
      code: trimmed,
      description: entry.desc,
      category: entry.category,
      suggestions: entry.desc === undefined ? [] : undefined,
    };
  }

  const suggestions = findSuggestions(trimmed);
  return {
    valid: true,
    code: trimmed,
    description: `Custom code (${baseCode})`,
    category: 'Unclassified',
    error: suggestions.length > 0 ? undefined : undefined,
    suggestions,
  };
}

function findSuggestions(query: string): string[] {
  const q = query.toUpperCase();
  const results: string[] = [];
  for (const [code, data] of Object.entries(ICD10_CATALOG)) {
    if (code.startsWith(q) || data.desc.toUpperCase().includes(q)) {
      results.push(`${code} - ${data.desc}`);
    }
    if (results.length >= 5) break;
  }
  return results;
}

export function searchICD10(query: string, limit = 10): { code: string; desc: string; category: string }[] {
  const q = query.toUpperCase().trim();
  if (q.length < 1) return [];
  const results: { code: string; desc: string; category: string }[] = [];
  for (const [code, data] of Object.entries(ICD10_CATALOG)) {
    if (code.startsWith(q) || data.desc.toUpperCase().includes(q)) {
      results.push({ code, desc: data.desc, category: data.category });
      if (results.length >= limit) break;
    }
  }
  return results;
}
