export interface Json {
  [key: string]: Json | string | number | boolean | null | Json[];
}

export interface Database {
  public: {
    Tables: {
      practices: {
        Row: {
          id: string;
          name: string;
          practice_number: string;
          hpcsa_number: string;
          address: Json;
          contact: Json;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          practice_number: string;
          hpcsa_number: string;
          address: Json;
          contact: Json;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          practice_number?: string;
          hpcsa_number?: string;
          address?: Json;
          contact?: Json;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          auth_user_id: string;
          practice_id: string;
          email: string;
          full_name: string;
          role: 'doctor' | 'nurse' | 'admin' | 'receptionist' | 'billing';
          phone: string | null;
          avatar_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          auth_user_id: string;
          practice_id: string;
          email: string;
          full_name: string;
          role: 'doctor' | 'nurse' | 'admin' | 'receptionist' | 'billing';
          phone?: string | null;
          avatar_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          auth_user_id?: string;
          practice_id?: string;
          email?: string;
          full_name?: string;
          role?: 'doctor' | 'nurse' | 'admin' | 'receptionist' | 'billing';
          phone?: string | null;
          avatar_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      patients: {
        Row: {
          id: string;
          practice_id: string;
          title: string | null;
          first_name: string;
          last_name: string;
          id_number: string | null;
          dob: string | null;
          gender: 'M' | 'F' | 'Other' | null;
          phone: string | null;
          email: string | null;
          address: Json | null;
          emergency_contact: Json | null;
          medical_aid: Json | null;
          allergies: string[];
          chronic_conditions: string[];
          tags: string[];
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          practice_id: string;
          title?: string | null;
          first_name: string;
          last_name: string;
          id_number?: string | null;
          dob?: string | null;
          gender?: 'M' | 'F' | 'Other' | null;
          phone?: string | null;
          email?: string | null;
          address?: Json | null;
          emergency_contact?: Json | null;
          medical_aid?: Json | null;
          allergies?: string[];
          chronic_conditions?: string[];
          tags?: string[];
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          practice_id?: string;
          title?: string | null;
          first_name?: string;
          last_name?: string;
          id_number?: string | null;
          dob?: string | null;
          gender?: 'M' | 'F' | 'Other' | null;
          phone?: string | null;
          email?: string | null;
          address?: Json | null;
          emergency_contact?: Json | null;
          medical_aid?: Json | null;
          allergies?: string[];
          chronic_conditions?: string[];
          tags?: string[];
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      appointments: {
        Row: {
          id: string;
          practice_id: string;
          patient_id: string;
          doctor_id: string;
          type: 'consultation' | 'follow_up' | 'procedure' | 'telemedicine' | 'chronic_review';
          status: 'scheduled' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
          scheduled_at: string;
          duration_minutes: number;
          notes: string | null;
          reason: string | null;
          room: string | null;
          is_urgent: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          practice_id: string;
          patient_id: string;
          doctor_id: string;
          type: 'consultation' | 'follow_up' | 'procedure' | 'telemedicine' | 'chronic_review';
          status?: 'scheduled' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
          scheduled_at: string;
          duration_minutes?: number;
          notes?: string | null;
          reason?: string | null;
          room?: string | null;
          is_urgent?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          practice_id?: string;
          patient_id?: string;
          doctor_id?: string;
          type?: 'consultation' | 'follow_up' | 'procedure' | 'telemedicine' | 'chronic_review';
          status?: 'scheduled' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
          scheduled_at?: string;
          duration_minutes?: number;
          notes?: string | null;
          reason?: string | null;
          room?: string | null;
          is_urgent?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      consultations: {
        Row: {
          id: string;
          practice_id: string;
          patient_id: string;
          doctor_id: string;
          appointment_id: string | null;
          type: 'consultation' | 'follow_up' | 'procedure' | 'telemedicine' | 'chronic_review';
          subjective: string | null;
          objective: string | null;
          assessment: string | null;
          plan: string | null;
          soap_note: Json | null;
          vitals: Json | null;
          icd10_codes: Json;
          tariff_codes: Json;
          prescriptions: Json;
          referrals: Json;
          attachments: Json;
          billing_status: 'pending' | 'billed' | 'submitted' | 'paid' | 'rejected' | 'partial';
          total_amount: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          practice_id: string;
          patient_id: string;
          doctor_id: string;
          appointment_id?: string | null;
          type: 'consultation' | 'follow_up' | 'procedure' | 'telemedicine' | 'chronic_review';
          subjective?: string | null;
          objective?: string | null;
          assessment?: string | null;
          plan?: string | null;
          soap_note?: Json | null;
          vitals?: Json | null;
          icd10_codes?: Json;
          tariff_codes?: Json;
          prescriptions?: Json;
          referrals?: Json;
          attachments?: Json;
          billing_status?: 'pending' | 'billed' | 'submitted' | 'paid' | 'rejected' | 'partial';
          total_amount?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          practice_id?: string;
          patient_id?: string;
          doctor_id?: string;
          appointment_id?: string | null;
          type?: 'consultation' | 'follow_up' | 'procedure' | 'telemedicine' | 'chronic_review';
          subjective?: string | null;
          objective?: string | null;
          assessment?: string | null;
          plan?: string | null;
          soap_note?: Json | null;
          vitals?: Json | null;
          icd10_codes?: Json;
          tariff_codes?: Json;
          prescriptions?: Json;
          referrals?: Json;
          attachments?: Json;
          billing_status?: 'pending' | 'billed' | 'submitted' | 'paid' | 'rejected' | 'partial';
          total_amount?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      claims: {
        Row: {
          id: string;
          practice_id: string;
          patient_id: string;
          consultation_id: string;
          claim_number: string;
          scheme_code: string;
          membership_number: string;
          dependant_code: string;
          service_date: string;
          tariff_codes: Json;
          nappi_codes: Json;
          icd10_primary: string;
          icd10_secondary: string | null;
          is_pmb: boolean;
          total_amount: number;
          paid_amount: number;
          co_payment: number;
          status: 'draft' | 'submitted' | 'adjudicated' | 'paid' | 'rejected' | 'partial' | 'pending_preauth';
          switch_reference: string | null;
          batch_number: string | null;
          rejection_code: string | null;
          rejection_reason: string | null;
          remittance_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          practice_id: string;
          patient_id: string;
          consultation_id: string;
          claim_number: string;
          scheme_code: string;
          membership_number: string;
          dependant_code: string;
          service_date: string;
          tariff_codes: Json;
          nappi_codes: Json;
          icd10_primary: string;
          icd10_secondary?: string | null;
          is_pmb?: boolean;
          total_amount: number;
          paid_amount?: number;
          co_payment?: number;
          status?: 'draft' | 'submitted' | 'adjudicated' | 'paid' | 'rejected' | 'partial' | 'pending_preauth';
          switch_reference?: string | null;
          batch_number?: string | null;
          rejection_code?: string | null;
          rejection_reason?: string | null;
          remittance_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          practice_id?: string;
          patient_id?: string;
          consultation_id?: string;
          claim_number?: string;
          scheme_code?: string;
          membership_number?: string;
          dependant_code?: string;
          service_date?: string;
          tariff_codes?: Json;
          nappi_codes?: Json;
          icd10_primary?: string;
          icd10_secondary?: string | null;
          is_pmb?: boolean;
          total_amount?: number;
          paid_amount?: number;
          co_payment?: number;
          status?: 'draft' | 'submitted' | 'adjudicated' | 'paid' | 'rejected' | 'partial' | 'pending_preauth';
          switch_reference?: string | null;
          batch_number?: string | null;
          rejection_code?: string | null;
          rejection_reason?: string | null;
          remittance_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          practice_id: string;
          patient_id: string | null;
          claim_id: string | null;
          amount: number;
          currency: string;
          method: 'cash' | 'card' | 'eft' | 'medical_aid' | 'payfast' | 'peach' | 'yoco' | 'ozow' | 'paygate' | 'netcash';
          status: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded' | 'cancelled';
          reference: string;
          gateway_reference: string | null;
          gateway_response: Json | null;
          description: string | null;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          practice_id: string;
          patient_id?: string | null;
          claim_id?: string | null;
          amount: number;
          currency?: string;
          method: 'cash' | 'card' | 'eft' | 'medical_aid' | 'payfast' | 'peach' | 'yoco' | 'ozow' | 'paygate' | 'netcash';
          status?: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded' | 'cancelled';
          reference: string;
          gateway_reference?: string | null;
          gateway_response?: Json | null;
          description?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          practice_id?: string;
          patient_id?: string | null;
          claim_id?: string | null;
          amount?: number;
          currency?: string;
          method?: 'cash' | 'card' | 'eft' | 'medical_aid' | 'payfast' | 'peach' | 'yoco' | 'ozow' | 'paygate' | 'netcash';
          status?: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded' | 'cancelled';
          reference?: string;
          gateway_reference?: string | null;
          gateway_response?: Json | null;
          description?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          practice_id: string;
          patient_id: string;
          invoice_number: string;
          issue_date: string;
          due_date: string;
          status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled' | 'partially_paid';
          subtotal: number;
          tax: number;
          total: number;
          paid_amount: number;
          balance: number;
          line_items: Json;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          practice_id: string;
          patient_id: string;
          invoice_number: string;
          issue_date: string;
          due_date: string;
          status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled' | 'partially_paid';
          subtotal: number;
          tax?: number;
          total: number;
          paid_amount?: number;
          balance?: number;
          line_items: Json;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          practice_id?: string;
          patient_id?: string;
          invoice_number?: string;
          issue_date?: string;
          due_date?: string;
          status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled' | 'partially_paid';
          subtotal?: number;
          tax?: number;
          total?: number;
          paid_amount?: number;
          balance?: number;
          line_items?: Json;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      medical_aid_schemes: {
        Row: {
          id: string;
          code: string;
          name: string;
          administrator: string;
          switch_routing: string;
          is_active: boolean;
          contact_info: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          administrator: string;
          switch_routing: string;
          is_active?: boolean;
          contact_info?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          administrator?: string;
          switch_routing?: string;
          is_active?: boolean;
          contact_info?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          practice_id: string;
          user_id: string | null;
          action: string;
          resource_type: string;
          resource_id: string | null;
          old_values: Json | null;
          new_values: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          practice_id: string;
          user_id?: string | null;
          action: string;
          resource_type: string;
          resource_id?: string | null;
          old_values?: Json | null;
          new_values?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          practice_id?: string;
          user_id?: string | null;
          action?: string;
          resource_type?: string;
          resource_id?: string | null;
          old_values?: Json | null;
          new_values?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_practice_stats: {
        Args: { practice_id: string };
        Returns: {
          total_patients: number;
          active_patients: number;
          appointments_today: number;
          pending_claims: number;
          revenue_mtd: number;
        }[];
      };
      get_claims_aging: {
        Args: { practice_id: string; as_of_date?: string };
        Returns: {
          scheme_name: string;
          current_30: number;
          days_31_60: number;
          days_61_90: number;
          over_90: number;
          total_outstanding: number;
        }[];
      };
    };
    Enums: {
      user_role: 'doctor' | 'nurse' | 'admin' | 'receptionist' | 'billing';
      appointment_type: 'consultation' | 'follow_up' | 'procedure' | 'telemedicine' | 'chronic_review';
      appointment_status: 'scheduled' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
      consultation_type: 'consultation' | 'follow_up' | 'procedure' | 'telemedicine' | 'chronic_review';
      billing_status: 'pending' | 'billed' | 'submitted' | 'paid' | 'rejected' | 'partial';
      claim_status: 'draft' | 'submitted' | 'adjudicated' | 'paid' | 'rejected' | 'partial' | 'pending_preauth';
      payment_method: 'cash' | 'card' | 'eft' | 'medical_aid' | 'payfast' | 'peach' | 'yoco' | 'ozow' | 'paygate' | 'netcash';
      payment_status: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded' | 'cancelled';
      invoice_status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled' | 'partially_paid';
      patient_gender: 'M' | 'F' | 'Other';
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}